### ISSUE TITLE
Add phpunit groups to the tests

### ISSUE THREAD

**Issue by Tjoosten** [SIJOT/SIJOT-2.x#35]
A test can be tagged as belonging to one or more groups using the `@group` annotation like this 

``` php
class MyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @group specification
     */
    public function testSomething()
    {
    }

    /**
     * @group regresssion
     * @group bug2204
     */
    public function testSomethingElse()
    {
    }
}
```
#### TODO Groups.
- [x] `database`: used for all the specific database tests.
- [x] `rental`: used for test all the rental views and methods.
- [x] `backend`: used for all the front-end pages.
- [ ] `front-end`: used for all the back-end pages.
  - [ ] Set in documentation.

Tests can be selected for execution based on groups using the --group and --exclude-group options of the command-line test runner or using the respective directives of the XML configuration file.
